# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MariahsHairSite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          # Install root dependencies
          npm install
          
          # Install server dependencies
          cd server
          npm install
          cd ..
          
          # Install client dependencies
          cd client
          npm install
          cd ..
          
          # Build React app
          cd client
          npm run build
          cd ..
          
          # Copy build files to server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      - name: Prepare deployment package
        run: |
          # Create a deployment directory
          mkdir deployment
          
          # Copy server files to deployment root
          cp -r server/* deployment/
          
          # Copy server package.json to root
          cp server/package.json deployment/
          
          # Copy web.config
          cp server/web.config deployment/

      - name: Zip artifact for deployment
        run: |
          # Create deployment package
          cd deployment
          zip -r ../release.zip . -x "node_modules/*" "uploads/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C82B4DB4EB794423AE6FF1BFC151978F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A79740DD7CE64244ABFF6777B4E9A2BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A03A129D977D4A78A83450507E95647F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MariahsHairSite'
          slot-name: 'Production'
          package: .
          